---
- name: Upgrade all packages
  community.general.pacman:
    update_cache: true
    upgrade: true

- name: Install VIM
  community.general.pacman:
    name: vim
    state: present

- name: Install Git
  community.general.pacman:
    name: git
    state: present

- name: Install Fish
  community.general.pacman:
    name: fish
    state: present

- name: Install NeoFetch
  community.general.pacman:
    name: neofetch
    state: present
  ignore_errors: true

- name: Install iSCSI
  community.general.pacman:
    name: open-iscsi
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"
  when: passwordless_admin
  tags:
    - groups
