---
- name: Upgrade all pacakges
  community.general.pacman:
    update_cache: true
    upgrade: true

- name: Install VIM
  community.general.pacman:
    name: vim
    state: present

- name: Install Git
  community.general.pacman:
    name: git
    state: present

- name: Install Fish
  community.general.pacman:
    name: fish
    state: present

- name: Install NeoFetch
  community.general.pacman:
    name: neofetch
    state: present

- name: Install iSCSI
  community.general.pacman:
    name: open-iscsi
    state: present
