---
- name: Upgrade all packages
  community.general.homebrew:
    name:
      - fish
      - neofetch
      - git
      - gsed
      - font-meslo-for-powerline
      - iterm2
    state: present
    update_homebrew: yes
  tags:
    - homebrew
    - darwin
