---
- name: Upgrade Homebrew and install required packages
  become: false
  community.general.homebrew:
    name:
      - fish
      - git
      - neofetch
      - gsed
    state: present
    upgrade_all: true
  tags:
    - homebrew
    - darwin
- name: Install casks
  become: false
  community.general.homebrew:
    name:
      - font-meslo-for-powerline
      - iterm2
    state: present
  ignore_errors: true
  tags:
    - homebrew
    - darwin
