---

- name: Fail if major version is less than 8
  become: false
  ansible.builtin.fail:
    msg: The RHEL (derivative) version must be version 8 or higher
  when: ansible_facts['distribution_major_version'] < 8

- name: Download EPEL RPM key
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: "http://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_facts['distribution_major_version'] }}"
  when: ansible_facts['distribution'] != "OracleLinux"
  tags:
    - yum
    - dnf

- name: Enable EPEL for RHEL and Clones
  become: true
  yum_repository:
    name: epel
    description: Extra Packages for Enterprise Linux $releasever - $basearch
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/Everything/$basearch
    metalink: https://mirrors.fedoraproject.org/metalink?repo=epel-$releasever&arch=$basearch&infra=$infra&content=$contentdir
    enabled: true
    gpgcheck: true
    gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_facts['distribution_major_version'] }}"
  when: ansible_facts['distribution'] != "OracleLinux"
  tags:
    - yum
    - dnf

- name: Enable EPEL Repo Oracle Linux
  become: true
  yum_repository:
    name: oel_developer_EPEL
    description: Oracle Linux $releasever EPEL Packages for Development ($basearch)
    baseurl: "https://yum$ociregion.$ocidomain/repo/OracleLinux/OL{{ ansible_facts['ansible_distribution_major_version'] }}/developer/EPEL/$basearch/"
    enabled: true
    gpgcheck: true
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
  when: ansible_facts['distribution'] == "OracleLinux"
  tags:
    - yum
    - dnf

- name: Upgrade all packages
  become: true
  dnf:
    name: "*"
    state: latest
  ignore_errors: true
  tags:
    - yum
    - dnf

- name: Install VIM
  become: true
  dnf:
    name: vim
    state: latest
  tags:
    - yum
    - dnf

- name: Install Git
  become: true
  dnf:
    name: git
    state: latest
  tags:
    - yum
    - dnf

- name: Install Fish
  become: true
  dnf:
    name: fish
    state: latest
  tags:
    - yum
    - dnf

- name: Install NeoFetch
  become: true
  dnf:
    name: neofetch
    state: latest
  ignore_errors: true
  tags:
    - yum
    - dnf

- name: Install iSCSI
  become: true
  dnf:
    name: iscsi-initiator-utils
    state: latest
  tags:
    - yum
    - dnf

- name: Allow 'wheel' group to have passwordless sudo
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"
  when: passwordless_admin
  tags:
    - groups
