---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  yaml-lint:
    runs-on: ubuntu-latest

    container:
      image: cytopia/yamllint

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run YAML linter
        run: yamllint .

  ansible-role-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Install Ansible
        run: pip3 install ansible ansible-runner ansible-navigator ansible-lint

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Run Ansible Lint
        run: ansible-lint -c ./.ansible-lint --exclude meta/ .
